### PR TITLE
feat: allow apps at a remote location

### PR DESCRIPTION
**Pull request by jeroen-tempels**
This change was inspired by the android appium driver. The driver has support for appium:app where the passed file is not a local file but lives somewhere in the cloud. This PR adds support for files hosted over https. It downloads the given file to a temporary folder and installs the app from there.

### CODE REVIEW

**Comment by KazuCocoa** [comment]
Thank you, I'll take a look later.

Perhaps using https://github.com/appium/appium/blob/89f2e25a6cf6c5bebf6f23eaa899d1c722baf41b/packages/base-driver/lib/basedriver/helpers.js#L69 would be nice to support file download as same as other Appium drivers do. I'll check this case also.

e.g. https://github.com/appium/appium-uiautomator2-driver/blob/718d72f0b4097c536fae9b6ef62c2c1a47bce68c/lib/driver.ts#L391

**Comment by KazuCocoa** [comment]
Does https://github.com/headspinio/appium-tizen-tv-driver/pull/663 work for you?

**Comment by jeroen-tempels** [comment]
> Does #663 work for you?

Jup, works for me! Thanks!

**Comment by KazuCocoa** [comment]
Thank you for the confirmation!

**Comment by KazuCocoa** [comment]
`0.12.1`+ should have this.

**Pull request closed without merging**
